# name: MY-Portfolio-Website

# on:     ##Branch you need to push changes
#   push:
#     branches:
#     - main

# jobs:      
#   build-and-deploy:
#     runs-on: ubuntu-latest  
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v1 #Script actions


